# -*- coding: utf-8 -*-
"""Computer Vision Assignment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fxcdwP272X2OSxWl1YqCcWseiTva0nso

## Step 1: Import Required Libraries

In this step, we import the necessary Python libraries for image processing and visualization. OpenCV (`cv2`) is used for image processing operations, NumPy is used for numerical operations, and Matplotlib is used to display images.
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

"""## Step 2: Upload the Image

In this step, the input image is uploaded to Google Colab. The image file used for this assignment is named `image.png`. The uploaded image will be used for all the image processing operations performed in the following steps.
"""

from google.colab import files

uploaded = files.upload()

"""## Step 3: Load and Display the Original RGB Image

In this step, the image is loaded using OpenCV. OpenCV normally reads images in BGR (Blue, Green, Red) format, so the image is converted from BGR to RGB format. The original color image is then displayed using Matplotlib.
"""

image = cv2.imread("image.png")

# Convert BGR to RGB
rgb_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

plt.figure(figsize=(8, 6))
plt.imshow(rgb_image)
plt.title("Original RGB Image")
plt.axis("off")
plt.show()

"""## Step 4: Inspect Image Dimensions

In this step, the dimensions of the input image are examined. We find the image height, width, and number of color channels. A color RGB image normally has three channels: Red, Green, and Blue. The shape of the image is displayed to understand its size and structure.
"""

height, width, channels = rgb_image.shape

print("Height:", height)
print("Width:", width)
print("Channels:", channels)
print("Image Shape:", rgb_image.shape)

"""## Step 5: Inspect Pixel Values

In this step, we examine the RGB pixel values at a specific location in the image. The pixel at coordinates (100, 100) is selected, and its Red, Green, and Blue intensity values are displayed. Each channel has a value between 0 and 255.
"""

pixel = rgb_image[100, 100]

print("Pixel value at (100, 100):", pixel)
print("Red:", pixel[0])
print("Green:", pixel[1])
print("Blue:", pixel[2])

"""## Step 6: Convert RGB Image to Grayscale

In this step, the original RGB image is converted into a grayscale image using OpenCV. A grayscale image contains only intensity information instead of separate Red, Green, and Blue channels. Therefore, the grayscale image has only two dimensions: height and width.
"""

gray_image = cv2.cvtColor(rgb_image, cv2.COLOR_RGB2GRAY)

print("Original shape:", rgb_image.shape)
print("Grayscale shape:", gray_image.shape)

plt.figure(figsize=(8, 6))
plt.imshow(gray_image, cmap="gray")
plt.title("Grayscale Image")
plt.axis("off")
plt.show()

"""## Step 7: Apply Gaussian Blur

In this step, Gaussian Blur is applied to the grayscale image. Gaussian Blur is an image smoothing technique that reduces noise and small details by averaging nearby pixels. A 5×5 Gaussian kernel is used in this operation.
"""

gaussian_blur = cv2.GaussianBlur(gray_image, (5, 5), 0)

plt.figure(figsize=(8, 6))
plt.imshow(gaussian_blur, cmap="gray")
plt.title("Gaussian Blur")
plt.axis("off")
plt.show()

"""## Step 8: Apply Histogram Equalization

In this step, histogram equalization is applied to the grayscale image. This technique improves the contrast of an image by redistributing the intensity values. It can make details more visible, especially when the original image has low or uneven contrast.
"""

hist_equalized = cv2.equalizeHist(gray_image)

plt.figure(figsize=(8, 6))
plt.imshow(hist_equalized, cmap="gray")
plt.title("Histogram Equalization")
plt.axis("off")
plt.show()

"""## Step 9: Comparison of Original and Processed Images

In this step, the original RGB image, grayscale image, Gaussian-blurred image, and histogram-equalized image are displayed together. This allows us to visually compare the effect of each image processing operation.
"""

plt.figure(figsize=(12, 10))

plt.subplot(2, 2, 1)
plt.imshow(rgb_image)
plt.title("Original RGB Image")
plt.axis("off")

plt.subplot(2, 2, 2)
plt.imshow(gray_image, cmap="gray")
plt.title("Grayscale Image")
plt.axis("off")

plt.subplot(2, 2, 3)
plt.imshow(gaussian_blur, cmap="gray")
plt.title("Gaussian Blur")
plt.axis("off")

plt.subplot(2, 2, 4)
plt.imshow(hist_equalized, cmap="gray")
plt.title("Histogram Equalization")
plt.axis("off")

plt.tight_layout()
plt.show()

"""## Step 10: Save the Output Images

In this step, the original and processed images are saved as separate image files. These output files can be downloaded and included in the assignment report as evidence of the image processing results.
"""

cv2.imwrite(
    "original_rgb.jpg",
    cv2.cvtColor(rgb_image, cv2.COLOR_RGB2BGR)
)

cv2.imwrite("grayscale.jpg", gray_image)
cv2.imwrite("gaussian_blur.jpg", gaussian_blur)
cv2.imwrite("histogram_equalized.jpg", hist_equalized)

print("All images saved successfully.")

files.download("original_rgb.jpg")

files.download("grayscale.jpg")

files.download("gaussian_blur.jpg")

files.download("histogram_equalized.jpg")

"""# Computer Vision and Image Processing Assignment

## Objective

The objective of this assignment is to understand the basic concepts of Computer Vision and Image Processing and to perform basic image processing operations using Python and OpenCV.

In this practical work, an RGB image is loaded and analyzed by checking its dimensions and pixel values. The image is then converted into grayscale. Two image enhancement/filtering techniques, Gaussian Blur and Histogram Equalization, are applied. Finally, the original and processed images are compared to observe the effects of these operations.

## Tools and Libraries

- Python
- Google Colab
- OpenCV
- NumPy
- Matplotlib
"""